steps:

- id: "Run tests"
  name: 'gcr.io/cloud-builders/go'
  env:
  - GOPATH=.
  args: ['test']

- id: "Building docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]

- id: "Uploading docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]
