steps:

- id: "Run tests"
  name: 'bash'
  args:
  - '-c'
  - |
    cd src/main \
    && go test

- id: "Building docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]

- id: "Uploading docker image"
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]
